"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-05-05 12:07:58.210652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analysis_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('extra', sa.String(length=512), nullable=False),
    sa.Column('active_strats', sa.JSON(), nullable=False),
    sa.Column('risk_params', sa.JSON(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('score', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_analysis_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_analysis_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_analysis_log_ticker'), ['ticker'], unique=False)

    op.create_table('backtest_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('initial_cash', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('bars_processed', sa.Integer(), nullable=False),
    sa.Column('final_cash', sa.Integer(), nullable=False),
    sa.Column('total_pnl', sa.Integer(), nullable=False),
    sa.Column('win_count', sa.Integer(), nullable=False),
    sa.Column('loss_count', sa.Integer(), nullable=False),
    sa.Column('max_drawdown', sa.Integer(), nullable=False),
    sa.Column('data_source', sa.String(length=16), nullable=False),
    sa.Column('data_symbol', sa.String(length=16), nullable=True),
    sa.Column('data_start', sa.DateTime(), nullable=True),
    sa.Column('data_end', sa.DateTime(), nullable=True),
    sa.Column('data_interval', sa.String(length=8), nullable=True),
    sa.Column('trades_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtest_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_run_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_run_strategy'), ['strategy'], unique=False)

    op.create_table('market_bar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Integer(), nullable=False),
    sa.Column('high', sa.Integer(), nullable=False),
    sa.Column('low', sa.Integer(), nullable=False),
    sa.Column('close', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'interval', 'timestamp', name='uq_market_bar_key')
    )
    with op.batch_alter_table('market_bar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_bar_interval'), ['interval'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_bar_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_bar_timestamp'), ['timestamp'], unique=False)

    op.create_table('order_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('requested_by_ai', sa.Boolean(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('limit_price', sa.Integer(), nullable=True),
    sa.Column('latest_price', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.Column('broker_order_id', sa.String(length=64), nullable=True),
    sa.Column('broker_status', sa.String(length=32), nullable=True),
    sa.Column('filled_quantity', sa.Integer(), nullable=False),
    sa.Column('avg_fill_price', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_audit_log_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_audit_log_mode'), ['mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_audit_log_symbol'), ['symbol'], unique=False)

    op.create_table('pending_approval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('limit_price', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['order_audit_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_approval', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_approval_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_approval_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_approval_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_approval_symbol'), ['symbol'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_approval', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_approval_symbol'))
        batch_op.drop_index(batch_op.f('ix_pending_approval_status'))
        batch_op.drop_index(batch_op.f('ix_pending_approval_created_at'))
        batch_op.drop_index(batch_op.f('ix_pending_approval_audit_id'))

    op.drop_table('pending_approval')
    with op.batch_alter_table('order_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_audit_log_symbol'))
        batch_op.drop_index(batch_op.f('ix_order_audit_log_mode'))
        batch_op.drop_index(batch_op.f('ix_order_audit_log_decision'))
        batch_op.drop_index(batch_op.f('ix_order_audit_log_created_at'))

    op.drop_table('order_audit_log')
    with op.batch_alter_table('market_bar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_bar_timestamp'))
        batch_op.drop_index(batch_op.f('ix_market_bar_symbol'))
        batch_op.drop_index(batch_op.f('ix_market_bar_interval'))

    op.drop_table('market_bar')
    with op.batch_alter_table('backtest_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_run_strategy'))
        batch_op.drop_index(batch_op.f('ix_backtest_run_created_at'))

    op.drop_table('backtest_run')
    with op.batch_alter_table('ai_analysis_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_analysis_log_ticker'))
        batch_op.drop_index(batch_op.f('ix_ai_analysis_log_created_at'))

    op.drop_table('ai_analysis_log')
    # ### end Alembic commands ###
