"""add emergency_stop_event

Revision ID: 0002
Revises: 0001
Create Date: 2026-05-05 20:26:29.802399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_stop_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emergency_stop_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergency_stop_event_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency_stop_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergency_stop_event_created_at'))

    op.drop_table('emergency_stop_event')
    # ### end Alembic commands ###
